<?php 
 $title  = 'New Role';
 $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<?php 

	$form->setAttribute('action',$this->url('role',array('action'=>'add')));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	?>
	<div class="form-group"><?php echo $this->formRow($form->get('name')); ?></div>
	
	<div class="form-group">
 		<?php echo $this->formSubmit($form->get('submit')); ?>
 		<?php echo $this->formReset($form->get('reset')); ?>
 		<a  class="btn" href="<?php echo $this->url('role')?>">Back</a>
 	</div>
	

 	<?php echo $this->form()->closeTag();?>


