<?php

$title = 'Delete Task';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<p>Are you sure you want to delete task?</p>

<?php

$url = $this->url('task',array('action'=>'delete','id'=>$id));
?>

<form action="<?php echo $url; ?>" method="post">
	<div>
		<input type="submit" value="Yes" name="delete">	
		<input type="submit" value="No" name="delete">	
	</div>
</form>




