<?php
$title = 'View task details';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<dl class="dl-horizontal">
	<dt>Id</dt>
	<dd><?php echo $task->getId()?></dd>

	<dt>Name</dt>
	<dd><?php echo $task->getTitle()?></dd>

	<dt>Completed</dt>
	<dd><?php echo $task->getCompleted() ? 'Yes' : 'No'; ?></dd>

	<dt>Created</dt>
	<dd><?php echo $task->getCreated()?></dd>
</dd>

<a class="btn btn-default" href="<?php echo $this->url('task');?>">Task list</a>


